title: "Autonomous Reports"
source: site          # <-- all your markdown & images are here
destination: _site    # Pages artifact will be created here
markdown: kramdown
collections:
  reports:
    output: true      # every file in site/reports/ becomes its own page
    permalink: /reports/:path/
